### PR TITLE
Add info to readme

### PR DESCRIPTION
**Pull request by jr2730**

### CODE REVIEW

**Comment by jr2730** [comment]
Updated previous PR by reverting the PurgeDirs and then also adding the info from Aimon into the README.

**Comment by relaxdiego** [comment]
Please squash this into a single commit. There's too much commit noise for a 2-file change.

**Comment by jr2730** [comment]
Isn't squashing done during the merge?
https://github.com/blog/2141-squash-your-commits

**Comment by relaxdiego** [comment]
I can do that too. Just make sure you update your local HEAD to the new squashed commit.

**Pull request merged**
